version: v2beta1
name: bluk-launcher

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      build_images --all -t $(git describe --always)    # 2. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 3. Deploy Helm charts and manifests specfied as "deployments"


# Define dependencies to other projects with a devspace.yaml
dependencies:
  api:
    name: "bluk-launcher-api"
    path: "./apps/api"

pullSecrets:
  registry-odzi-dog:
    registry: registry.odzi.dog
    username: "empty"
    password: "empty"